# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T1aRIsgwk94PVEKzaOkb8aomOxCjVmSj
"""

import streamlit as st

st.set_page_config(
    page_title="Bhagat Search",
    layout="centered"
)

st.title("🔍 Bhagat Search Application")
st.write("Use the sidebar to upload CSV and search Bhagat")
st.info("Select a page from the sidebar ⬅️")