# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T1aRIsgwk94PVEKzaOkb8aomOxCjVmSj
"""

import streamlit as st

st.set_page_config(page_title="Bhagat Search", layout="centered")

st.title("🙏🏻 Dorset Shibir Accomodation 🔍")

# 🔹 Add image
st.image(
    "logo.png",
    width=200
)


if st.session_state.get("logged_in"):
    st.sidebar.success(
        f"Logged in as {st.session_state['user']} "
        f"({st.session_state['role']})"
    )
else:
    st.sidebar.info("Please login")
