# -*- coding: utf-8 -*-
"""auth.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VxlXOqt7lc6xjwwqp7PjmzAjxxUuISIK
"""

import streamlit as st

def require_role(required_role: str):
    # -------------------------------
    # Not logged in
    # -------------------------------
    if not st.session_state.get("logged_in"):
        st.warning("Please login first using the Login page from the sidebar.")
        st.stop()

    user_role = st.session_state.get("role")

    # -------------------------------
    # Uploader can access EVERYTHING
    # -------------------------------
    if user_role == "uploader":
        return

    # -------------------------------
    # Searcher can access search only
    # -------------------------------
    if required_role == "searcher" and user_role == "searcher":
        return

    # -------------------------------
    # Access denied
    # -------------------------------
    st.error("⛔ Access denied")
    st.info("Please use the Search Bhagat page from the sidebar.")
    st.stop()
