# -*- coding: utf-8 -*-
"""auth.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VxlXOqt7lc6xjwwqp7PjmzAjxxUuISIK
"""

import streamlit as st

def require_role(role: str):
    if not st.session_state.get("logged_in"):
        st.warning("Please login first.")
        st.switch_page("pages/1_Login.py")

    if st.session_state.get("role") != role:
        # Redirect based on role
        if st.session_state.get("role") == "searcher":
            st.switch_page("pages/3_Search_Bhagat.py")
        elif st.session_state.get("role") == "uploader":
            st.switch_page("pages/2_Accomodation.py")
        else:
            st.switch_page("pages/1_Login.py")
