# -*- coding: utf-8 -*-
"""auth.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VxlXOqt7lc6xjwwqp7PjmzAjxxUuISIK
"""

import streamlit as st

def require_role(required_role: str):
    # -------------------------------
    # Not logged in
    # -------------------------------
    if not st.session_state.get("logged_in"):
        st.warning("Please login first.")

        # ✅ Use PAGE NAME, not file path
        st.page_link(
            "Login",
            label="🔐 Go to Login",
            icon="➡️"
        )

        st.stop()

    user_role = st.session_state.get("role")

    # -------------------------------
    # Uploader can access everything
    # -------------------------------
    if user_role == "uploader":
        return

    # -------------------------------
    # Searcher can access search pages
    # -------------------------------
    if required_role == "searcher" and user_role == "searcher":
        return

    # -------------------------------
    # Access denied
    # -------------------------------
    st.error("⛔ Access denied")

    st.page_link(
        "Search Bhagat",
        label="🔍 Go to Search",
        icon="➡️"
    )

    st.stop()
