# -*- coding: utf-8 -*-
"""database.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14k3cgSnwxTQn8b9y4UCDJ_mQhjMQUgdO
"""

import sqlite3
import pandas as pd

DB_NAME = "bhagat.db"

def get_connection():
    return sqlite3.connect(DB_NAME, check_same_thread=False)

def create_table():
    conn = get_connection()
    cursor = conn.cursor()

    cursor.execute("""
        CREATE TABLE IF NOT EXISTS bhagat_data (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            house_name TEXT,
            room_number TEXT,
            bhagat_name_1 TEXT,
            bhagat_name_2 TEXT
        )
    """)

    conn.commit()
    conn.close()

def insert_csv(df):
    conn = get_connection()
    df = df.rename(columns={
        "House Name": "house_name",
        "Room Number": "room_number",
        "Bhagat Name 1": "bhagat_name_1",
        "Bhagat Name 2": "bhagat_name_2"
    })

    df.to_sql("bhagat_data", conn, if_exists="replace", index=False)
    conn.close()

def search_bhagat(name):
    conn = get_connection()
    query = """
        SELECT house_name, room_number, bhagat_name_1, bhagat_name_2
        FROM bhagat_data
        WHERE LOWER(bhagat_name_1) = ?
           OR LOWER(bhagat_name_2) = ?
    """
    df = pd.read_sql_query(query, conn, params=(name, name))
    conn.close()
    return df