# -*- coding: utf-8 -*-
"""search.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bVtgEm6zEI60bBVhk-DqG-aB-x8wS-8g
"""

import streamlit as st

st.title("🔎 Search Bhagat")

if "data" not in st.session_state:
    st.warning("Please upload a CSV file first.")
    st.stop()

df = st.session_state["data"]

bhagat_name = st.text_input("Enter Bhagat Name")

if bhagat_name.strip():
    search = bhagat_name.strip().lower()

    result = df[
        df["Bhagat Name 1"].astype(str).str.strip().str.lower().str.contains(search, na=False) |
        df["Bhagat Name 2"].astype(str).str.strip().str.lower().str.contains(search, na=False)
    ]

    if result.empty:
        st.error("Bhagat not found ❌")
    else:
        st.success(f"{len(result)} record(s) found ✅")
        st.dataframe(
            result[["House Name", "Room Number", "Bhagat Name 1", "Bhagat Name 2"]],
            use_container_width=True
        )