# -*- coding: utf-8 -*-
"""1_Login.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hI2ofXfOxSR3QUAi_8HjIbDZilYoCb0F
"""

import streamlit as st

st.title("🔐 Login")

# -------------------------------
# Hardcoded users (can be moved to DB later)
# -------------------------------
USERS = {
    "upload_team": {
        "password": "upload123",
        "role": "uploader"
    },
    "search_team": {
        "password": "search123",
        "role": "searcher"
    }
}

# -------------------------------
# Login form
# -------------------------------
username = st.text_input("Username")
password = st.text_input("Password", type="password")

if st.button("Login"):
    if username in USERS and USERS[username]["password"] == password:
        st.session_state["logged_in"] = True
        st.session_state["user"] = username
        st.session_state["role"] = USERS[username]["role"]
        st.success(f"Logged in as {USERS[username]['role']} ✅")
        st.info("➡️ Use the sidebar to navigate")
    else:
        st.error("Invalid username or password ❌")

# -------------------------------
# Logout button (optional)
# -------------------------------
if st.session_state.get("logged_in"):
    st.divider()
    if st.button("Logout"):
        st.session_state.clear()
        st.success("Logged out successfully")