# -*- coding: utf-8 -*-
"""pages/1_📤_Upload_CSV.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xliG7WmeiVtHZ0y8-SVfy0ZEDmw5-Z8u
"""

import streamlit as st
import pandas as pd
from database import create_table, insert_csv

st.title("🏫 Accomodation")

# Access control
if not st.session_state.get("logged_in"):
    st.warning("Please login first.")
    st.stop()

if st.session_state.get("role") != "uploader":
    st.error("⛔ Access denied. Accomodation only.")
    st.stop()

uploaded_file = st.file_uploader("Upload CSV File", type=["csv"])

if uploaded_file:
    try:
        df = pd.read_csv(uploaded_file)

        required_columns = [
            "House Name",
            "Room Number",
            "Bhagat Name 1",
            "Bhagat Name 2"
        ]

        if not all(col in df.columns for col in required_columns):
            st.error("CSV file does not contain required columns.")
        else:
            create_table()
            insert_csv(df)
            st.success("CSV stored in database successfully ✅")

    except Exception as e:
        st.error(f"Error: {e}")
