# -*- coding: utf-8 -*-
"""pages/2_🔍_Search_Bhagat.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bVtgEm6zEI60bBVhk-DqG-aB-x8wS-8g
"""

import streamlit as st

# -------------------------------
# Page Title
# -------------------------------
st.title("🔍 Search Bhagat")

# -------------------------------
# Check if CSV is uploaded
# -------------------------------
if "data" not in st.session_state:
    st.warning("Please upload a CSV file first.")
    st.stop()

df = st.session_state["data"]

# -------------------------------
# Search Input
# -------------------------------
bhagat_name = st.text_input("Enter Bhagat Name Used in Registration")

# -------------------------------
# Search Logic (EXACT MATCH)
# -------------------------------
if bhagat_name.strip():
    search = bhagat_name.strip().lower()

    result = df[
        (df["Bhagat Name 1"].astype(str).str.strip().str.lower() == search) |
        (df["Bhagat Name 2"].astype(str).str.strip().str.lower() == search)
    ]

    # -------------------------------
    # Display Results
    # -------------------------------
    if result.empty:
        st.error("Bhagat not found ❌")
    else:
        st.success(f"{len(result)} record(s) found ✅")
        st.dataframe(
            result[["House Name", "Room Number", "Bhagat Name 1", "Bhagat Name 2"]],
            use_container_width=True
        )
