# -*- coding: utf-8 -*-
"""pages/2_🔍_Search_Bhagat.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bVtgEm6zEI60bBVhk-DqG-aB-x8wS-8g
"""

import streamlit as st
from database import search_bhagat

# Role guard (uploader + searcher allowed)
require_role("searcher")

st.title("🔍 Search Bhagat")

bhagat_name = st.text_input("Enter Bhagat Name (Exact match)")

if bhagat_name.strip():
    result = search_bhagat(bhagat_name.strip().lower())

    if result.empty:
        st.error("Bhagat not found ❌")
    else:
        st.success(f"{len(result)} record(s) found ✅")
        st.dataframe(result, use_container_width=True)
