# -*- coding: utf-8 -*-
"""pages/2_🔍_Search_Bhagat.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bVtgEm6zEI60bBVhk-DqG-aB-x8wS-8g
"""

import streamlit as st
from database import search_bhagat

st.title("🔍 Search Bhagat")

# Access control
if not st.session_state.get("logged_in"):
    st.warning("Please login first.")
    st.stop()

if st.session_state.get("role") != "searcher":
    st.error("⛔ Access denied. Search team only.")
    st.stop()

bhagat_name = st.text_input("Enter Bhagat Name (Exact match)")

if bhagat_name.strip():
    search = bhagat_name.strip().lower()

    result = search_bhagat(search)

    if result.empty:
        st.error("Bhagat not found ❌")
    else:
        st.success(f"{len(result)} record(s) found ✅")
        st.dataframe(result, use_container_width=True)
