# -*- coding: utf-8 -*-
"""pages/1_📤_Upload_CSV.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xliG7WmeiVtHZ0y8-SVfy0ZEDmw5-Z8u
"""

import streamlit as st
import pandas as pd

st.title("📤 Upload CSV File")

uploaded_file = st.file_uploader("Upload CSV File (.csv)", type=["csv"])

if uploaded_file is not None:
    try:
        df = pd.read_csv(uploaded_file)

        required_columns = [
            "House Name",
            "Room Number",
            "Bhagat Name 1",
            "Bhagat Name 2"
        ]

        if not all(col in df.columns for col in required_columns):
            st.error("CSV file does not contain required columns.")
        else:
            st.session_state["data"] = df
            st.success("CSV uploaded successfully ✅")
            st.write("➡️ Go to **Search Bhagat** page")

    except Exception as e:
        st.error(f"Error reading file: {e}")